version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    ports:
      - "8090:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
      - redis
    networks:
      - perjadin-net
  
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: perjadin
      MYSQL_USER: rasel
      MYSQL_PASSWORD: r283l8tr
      MYSQL_ROOT_HOST: '%'
      MYSQL_INITDB_SKIP_TZINFO: 1
      MYSQL_EXTRA_FLAGS: --sql-mode="TRADITIONAL"

  db:
    image: mysql:8.0
    container_name: ci4_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: perjadin
      MYSQL_USER: rasel
      MYSQL_PASSWORD: r283l8tr
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - perjadin-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ci4_phpmyadmin
    restart: always
    ports:
      - "8091:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db
    networks:
      - perjadin-net

  redis:
    image: redis:alpine
    container_name: ci4_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - perjadin-net

volumes:
  db_data:

networks:
  perjadin-net:
