services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - perjadin-net
  
  db:
    image: mariadb:10.4
    container_name: ci4_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: perjadin
      MYSQL_USER: rasel
      MYSQL_PASSWORD: r283l8tr
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - perjadin-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ci4_phpmyadmin
    restart: always
    ports:
      - "8091:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db
    networks:
      - perjadin-net

volumes:
  db_data:

networks:
  perjadin-net:
